#!/bin/sh

set -e -u

cd `dirname $0`

# create library directories.
mkdir -p bin
mkdir -p lib

# build the libraries:
if [ `uname -s` = "Darwin" ]; then
    cc -o lib/libah.dylib -dynamiclib -I"libah" libah/*_all.c libah/*_posix.c
else
    cc -o lib/libah.so -fPIC -shared  -I"libah" libah/*_all.c libah/*_posix.c
fi

cc -c -I"libac" -I"libaex" -I"libah" libac/*.c
ar cr lib/libac.a *.o
rm *.o

cc -c -I"libac" -I"libaex" -I"libah" libaex/*.c
ar cr lib/libaex.a *.o
rm *.o
