#!/bin/sh

set -e -u

cd `dirname $0`

# create library directories.
mkdir -p bin
mkdir -p lib

# build the host library:
_out="lib/libh"
_inc="alibh"

_src="\
    alibh/*_all.c \
    alibh/*_posix.c"

if [ `uname -s` = "Darwin" ]; then
    cc -dynamiclib   -o $_out.dylib -I$_inc $_src
else
    cc -fPIC -shared -o $_out.so    -I$_inc $_src
fi
