#!/bin/sh

# root directory.
export ANTH_HOME=$0:a:h

# environment:
export PATH=$PATH:$ANTH_HOME/bin

export CPATH=$ANTH_HOME/libac:$ANTH_HOME/libaex:$ANTH_HOME/libah

export      LIBRARY_PATH=$ANTH_HOME/lib
export DYLD_LIBRARY_PATH=$ANTH_HOME/lib
export   LD_LIBRARY_PATH=$ANTH_HOME/lib

# commands.
alias cls="clear"

# shell configuration.
export LSCOLORS=exaxaxaxaxaxaxaxaxaxax
export CLICOLOR=1
PROMPT="%F{green}%~ %# %f"

# user configuration.
if [ -f $ANTH_HOME/ucfg ]; then
    source $ANTH_HOME/ucfg
fi
